export const knowledgeTopics = [
    {
        id: 'science',
        name: 'Science',
        description: 'Energy, cells, ecosystems, and everyday physical systems.',
        questions: [
            {
                id: 'science-energy-transfer',
                prompt: 'What does energy transfer describe?',
                detail: 'Think about what happens when one object or system affects another.',
                answers: [
                    'Energy moving from one place or form to another',
                    'Matter disappearing completely',
                    'A force becoming weight',
                    'A cell dividing into two cells',
                ],
                correctIndex: 0,
                explanation: 'Energy transfer means energy moves between objects, places, or forms, like sunlight becoming heat or food becoming motion.',
            },
            {
                id: 'science-photosynthesis',
                prompt: 'What do plants mainly use photosynthesis to make?',
                detail: 'Photosynthesis uses sunlight, carbon dioxide, and water.',
                answers: ['Glucose', 'Salt', 'Protein only', 'Oxygen only'],
                correctIndex: 0,
                explanation: 'Plants use photosynthesis to make glucose, a sugar that stores chemical energy. Oxygen is released as a byproduct.',
            },
            {
                id: 'science-ecosystem',
                prompt: 'In an ecosystem, what role does a decomposer play?',
                detail: 'Decomposers are part of the recycling system of nature.',
                answers: [
                    'Breaks down dead matter and returns nutrients',
                    'Creates sunlight',
                    'Hunts every producer',
                    'Stops all energy flow',
                ],
                correctIndex: 0,
                explanation: 'Decomposers break down dead organisms and waste, returning nutrients to soil or water.',
            },
        ],
    },
    {
        id: 'history',
        name: 'History',
        description: 'Cause, effect, evidence, and how societies change over time.',
        questions: [
            {
                id: 'history-primary-source',
                prompt: 'Which item is the best example of a primary source?',
                detail: 'A primary source comes directly from the time or event being studied.',
                answers: [
                    'A diary written during the event',
                    'A modern textbook chapter',
                    'A documentary made decades later',
                    'A summary article',
                ],
                correctIndex: 0,
                explanation: 'A diary written during the event is primary because it comes directly from someone connected to that time.',
            },
            {
                id: 'history-cause-effect',
                prompt: 'Why do historians compare causes and effects?',
                detail: 'Events usually do not happen for one simple reason.',
                answers: [
                    'To understand how one event connects to later changes',
                    'To memorize dates without context',
                    'To avoid using evidence',
                    'To prove every source is wrong',
                ],
                correctIndex: 0,
                explanation: 'Cause and effect helps historians explain how conditions and decisions led to later outcomes.',
            },
            {
                id: 'history-bias',
                prompt: 'What does source bias mean?',
                detail: 'Bias is about perspective, not automatically about lying.',
                answers: [
                    'A source may reflect a point of view or preference',
                    'A source has no author',
                    'A source is always useless',
                    'A source is written in another language',
                ],
                correctIndex: 0,
                explanation: 'Bias means a source reflects someone&apos;s perspective, values, goals, or limits. It can still be useful if read carefully.',
            },
        ],
    },
    {
        id: 'math',
        name: 'Math',
        description: 'Number sense, equations, percentages, and problem solving.',
        questions: [
            {
                id: 'math-percent',
                prompt: 'What is 25% of 80?',
                detail: '25% is the same as one fourth.',
                answers: ['20', '25', '40', '60'],
                correctIndex: 0,
                explanation: '25% means one fourth. One fourth of 80 is 20.',
            },
            {
                id: 'math-variable',
                prompt: 'In the equation x + 7 = 12, what is x?',
                detail: 'Undo the addition to isolate the variable.',
                answers: ['5', '7', '12', '19'],
                correctIndex: 0,
                explanation: 'Subtract 7 from both sides: x = 5.',
            },
            {
                id: 'math-average',
                prompt: 'What is the average of 4, 6, and 14?',
                detail: 'Average means total divided by the number of values.',
                answers: ['8', '6', '10', '24'],
                correctIndex: 0,
                explanation: 'The total is 24, and 24 divided by 3 values is 8.',
            },
        ],
    },
];
